### ISSUE TITLE
Looked into Mun-lang yet?

### ISSUE THREAD

**Issue by erlend-sh** [nepp2/live-programming-prototype#2]
I was surprised to *not* find Mun-lang in your references. Have you checked it out?

https://mun-lang.org/
https://github.com/mun-lang/mun

Seems to have a lot in common with what you’re exploring here.

**Comment by nepp2** [comment]
I am aware of Mun, yes! You're right that it seems to have a lot in common, although I'm not familiar with the technical details of that project. I actually have loads of references littered around in different places, including Mun. I added the references markdown file very recently as the beginning of an effort to centralise them somewhere. Thanks for the reminder though :)

Just fyi, this respository is a bit of a mess, with a lot of broken code and probably a lot of very outdated information. It's an active project, but at the moment it exists to facilitate a PhD, rather than to be useable software. I definitely wouldn't waste time trying to build or run it. I'm actually quite curious; if you don't mind me asking, how did you stumble across it?

**Comment by erlend-sh** [comment]
I just google things like “game” specific to Rust-lang on GitHub from time to time to see what’s cooking in the ecosystem ;)

**Comment by erlend-sh** [comment]
https://mun-lang.org/blog/2020/05/16/release-mun-v0-2-0/

They've got a pretty active community on Discord now. I'm sure they'd love to hear from you and compare notes!

**Comment by nepp2** [comment]
Thanks man, I appreciate the heads up :)
